export const defaultBookings = [
  {
    id: 1,
    name: "John Doe",
    date: "2024-12-31",
    time: "10",
    guests: 2,
    occasion: "Birthday",
  },
  {
    id: 2,
    name: "Jane Doe",
    date: "2024-12-31",
    time: "11",
    guests: 4,
    occasion: "Anniversary",
  },
  {
    id: 3,
    name: "James Doe",
    date: "2024-12-31",
    time: "12",
    guests: 6,
    occasion: "Wedding",
  },
  {
    id: 4,
    name: "Jill Doe",
    date: "2024-12-31",
    time: "13",
    guests: 8,
    occasion: "Graduation",
  },
  {
    id: 5,
    name: "Jack Doe",
    date: "2024-12-31",
    time: "14",
    guests: 10,
    occasion: "Date Night",
  },
  {
    id: 6,
    name: "Jenny Doe",
    date: "2024-12-31",
    time: "15",
    guests: 2,
    occasion: "Birthday",
  },
  {
    id: 7,
    name: "Jerry Doe",
    date: "2024-12-31",
    time: "16",
    guests: 4,
    occasion: "Anniversary",
  },
  {
    id: 8,
    name: "Jesse Doe",
    date: "2024-12-31",
    time: "17",
    guests: 6,
    occasion: "Wedding",
  },
  {
    id: 9,
    name: "Jasmine Doe",
    date: "2024-12-31",
    time: "18",
    guests: 8,
    occasion: "Graduation",
  },
  {
    id: 10,
    name: "Jason Doe",
    date: "2024-12-31",
    time: "19",
    guests: 2,
    occasion: "Date Night",
  },
];
