export const defaultBookings = [
  {
    id: 1,
    name: "John Doe",
    date: "2024-12-31",
    time: "18",
    guests: 2,
    occasion: "Birthday",
  },
  {
    id: 2,
    name: "Jane Doe",
    date: "2024-12-31",
    time: "19",
    guests: 4,
    occasion: "Anniversary",
  },
  {
    id: 3,
    name: "James Doe",
    date: "2024-12-31",
    time: "20",
    guests: 6,
    occasion: "Wedding",
  },
  {
    id: 4,
    name: "Jill Doe",
    date: "2024-12-31",
    time: "21",
    guests: 8,
    occasion: "Graduation",
  },
  {
    id: 5,
    name: "Jack Doe",
    date: "2024-12-31",
    time: "22",
    guests: 10,
    occasion: "Date Night",
  },
  {
    id: 6,
    name: "Jenny Doe",
    date: "2024-12-31",
    time: "23",
    guests: 12,
    occasion: "Birthday",
  },
  {
    id: 7,
    name: "Jerry Doe",
    date: "2024-12-31",
    time: "00",
    guests: 14,
    occasion: "Anniversary",
  },
  {
    id: 8,
    name: "Jesse Doe",
    date: "2024-12-31",
    time: "01",
    guests: 16,
    occasion: "Wedding",
  },
  {
    id: 9,
    name: "Jasmine Doe",
    date: "2024-12-31",
    time: "02",
    guests: 18,
    occasion: "Graduation",
  },
  {
    id: 10,
    name: "Jason Doe",
    date: "2024-12-31",
    time: "03",
    guests: 20,
    occasion: "Date Night",
  },
];
